In [3]:
import numpy as np

class Tensor(object):
    def __init__(self, data):
        self.data = np.array(data)
        
    def __add__(self, other):
        return Tensor(self.data + other.data)
    
    def __repr__(self):
        return str(self.data.__repr__())
    
    def __str__(self):
        return str(self.data.__str__())
    
x = Tensor([1, 2, 3, 4, 5])
print(x)

y = x + x
print(y)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [12]:
# Automatic gradient computation (autograd)
# Making backpropagation automatic

import numpy as np

class Tensor(object):
    def __init__(self, data, creators = None, creation_op = None):
        self.data = np.array(data)
        self.creation_op = creation_op
        self.creators = creators
        self.grad = None
        
    def backward(self, grad):
        self.grad = grad
        
        if (self.creation_op == 'add'):
            self.creators[0].backward(grad)
            self.creators[1].backward(grad)
        
    def __add__(self, other):
        return Tensor(
            self.data + other.data,
            creators = [self, other],
            creation_op = 'add'
        )
    
    def __repr__(self):
        return str(self.data.__repr__())
    
    def __str__(self):
        return str(self.data.__str__())
    
x = Tensor([1, 2, 3, 4, 5])
y = Tensor([2, 2, 2, 2, 2])

z = x + y
z.backward(Tensor(np.array([1, 1, 1, 1, 1])))

print(x.grad)
print(y.grad)
print(z.creators)
print(z.creation_op)

print('\n-------------------------\n')

# It also works recursively
a = Tensor([1, 2, 3, 4, 5])
b = Tensor([2, 2, 2, 2, 2])
c = Tensor([5, 4, 3, 2, 1])
d = Tensor([-1, -2, -3, -4, -5])
e = a + b
f = c + d
g = e + f
g.backward(Tensor(np.array([1, 1, 1, 1, 1])))
print('a Grad: ' + str(a.grad))

print('\n-------------------------\n')


a1 = Tensor([1, 2, 3, 4, 5])
b1 = Tensor([2, 2, 2, 2, 2])
c1 = Tensor([5, 4, 3, 2, 1])

d1 = a1 + b1
e1 = b1 + c1
f1 = d1 + e1
f1.backward(Tensor(np.array([1, 1, 1, 1, 1])))

print(b.grad.data == np.array([2, 2, 2, 2, 2]))



[1 1 1 1 1]
[1 1 1 1 1]
[array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2])]
add

-------------------------

a Grad: [1 1 1 1 1]

-------------------------

[False False False False False]


In [1]:
# Upgrading autograd to support multiple tensors

import numpy as np

class Tensor(object):
    def __init__(
        self,
        data,
        autograd = False,
        creators = None,
        creation_op = None,
        id = None
    ):
        self.data = np.array(data)
        self.creation_op = creation_op
        self.creators = creators
        self.grad = None
        self.autograd = autograd
        self.children = {}
        if (id is None):
            id = np.random.randint(0, 100000)
        self.id = id
        
        if (creators is not None):
            for c in creators:
                # Keeps track of how many children a tensor has
                if (self.id not in c.children):
                    c.children[self.id] = 1
                else:
                    c.children[self.id] += 1
    
    # Checks whether a tensor has received the correct number of gradients from each child
    def all_children_grads_accounted_for(self):
        for id, cnt in self.children.items():
            if (cnt != 0):
                return False
        return True
    
        
    def backward(self, grad = None, grad_origin = None):
        if (self.autograd):
            if (grad_origin is not None):
                # Check to make sure you can backpropagate or whether you're
                # waiting for a gradient in which case decrement the counter
                if (self.children[grad_origin.id] == 0):
                    raise Exception('cannot backprop more than once')
                else:
                    self.children[grad_origin.id] -= 1
            
            if (self.grad is None):
                # Accumulates gradient fromseveral children
#                 self.grad = grad
                grad = Tensor(np.ones_like(self.data)) # Need to check in repository for this change
            else:
                self.grad += grad
                
            if (self.creators is not None and (self.all_children_grads_accounted_for() or grad_origin is None)):
                if (self.creation_op == 'add'):
                    # Begins actual backpropagation
                    self.creators[0].backward(self.grad, self)
                    self.creators[1].backward(self.grad, self)
                    
                if (self.creation_op == 'neg'):
                    self.creators[0].backward(self.grad.__neg__())
                    
                if (self.creation_op == 'sub'):
                    new = Tensor(self.grad.data)
                    self.creators[0].backward(new, self)
                    new = Tensor(self.grad.__neg__().data)
                    self.creators[1].backward(, self)
                    
                if (self.creation_op == 'mul'):
                    new = self.grad * self.creators[1]
                    self.creators[0].backward(new, self)
                    new = self.grad * self.creators[0]
                    self.creators[1].backward(new, self)
                    
                if (self.creation_op == 'mm'):
                    act = self.creators[0] # Usually an activation
                    weights = self.creators[1] # Usually a weight matrix
                    new = self.grad.mm(weights.transpose())
                    act.backward(new)
                    new = self.grad.transpose().mm(act).transpose()
                    weights.backward(new)
                    
                if (self.creation_op == 'transpose'):
                    self.creators[0],backward(self.grad.transpose())
                    
                if (self.creation_op == 'sigmoid'):
                    ones = Tensor(np.ones_like(self.grad.data))
                    self.creators[0].backward(self.grad * (self * (ones - self)))
                    
                if (self.creation_op == 'tanh'):
                    ones = Tensor(np.ones_like(self.grad.data))
                    self.creators[0].backward(self.grad * (ones - (self * self)))
                    
                if (self.creation_op == 'index_select'):
                    new_grad = np.zeros_like(self.creators[0].data)
                    indices_ = self.index_select_indices.data.flatten()
                    grad_ = grad.data.reshape(len(indices_), -1)
                    for i in range(len(indices_)):
                        new_grad[indices_[i]] += grad_[i]
                    self.creators[0].backward(Tensor(new_grad))
                    
                if (self.creation_op == 'cross_entropy'):
                    dx = self.softmax_output - self.target_dist
                    self.creators[0].backward(Tensor(dx))
                    
                if ('sum' in self.creation_op):
                    dim = int(self.creation_op.split('_')[1])
                    ds = self.creators[0].data.shape[dim]
                    self.creators[0].backward(self.grad.expand(dim, ds))
                    
                if ('expand' in self.creation_op):
                    dim = int(self.creation_op.split('_')[1])
                    self.creators[0].backward(self.grad.sum(dim))
                    
        
    def __add__(self, other):
        if (self.autograd and other.autograd):
            return Tensor(
                self.data + other.data,
                autograd = True,
                creators = [self, other],
                creation_op = 'add'
            )
        return Tensor(self.data + other.data)
    
    def __neg__(self):
        if (self.autograd):
            return Tensor(
                self.data * -1,
                autograd = True,
                creators = [self],
                creation_op = 'neg'
            )
        return Tensor(self.data * -1)
    
    def __repr__(self):
        return str(self.data.__repr__())
    
    def __str__(self):
        return str(self.data.__str__())
    
    def __sub__(self, other):
        if (self.autograd and other.autograd):
            return Tensor(
                self.data - other.data,
                autograd = True,
                creators = [self, other],
                creation_op = 'sub'
            )
        return Tensor(self.data - other.data)
    
    def __mul__(self, other):
        if (self.autograd and other.autograd):
            return Tensor(
                self.data * other.data,
                autograd = True,
                creators = [self, other],
                creation_op = 'mul'
            )
        return Tensor(self.data * other.data)
    
    def sum(self, dim):
        if (self.autograd):
            return Tensor(
                self.data.sum(dim),
                autograd = True,
                creators = [self],
                creation_op = 'sum_' + str(dim)
            )
        return Tensor(self.data.sum(dim))
    
    def expand(self, dim, copies):
        trans_cmd = list(range(0, len(self.data.shape))
        trans_cmd.insert(dim, len(self.data.shape))
        new_shape = list(self.data.shape) + [copies]
        new_data = self.data.repeat(copies).reshape(new_shape)
        new_data = new_data.transpose(trans_cmd)
                         
        if (self.autograd):
            return Tensor(
                new_data,
                autograd = True,
                creators = [self],
                creation_op = 'transpose'                
            )
        return Tensor(new_data)
                         
    def transpose(self):
        if (self.autograd):
            return Tensor(
                self.data.transpose(),
                autograd = True,
                creators = [self],
                creation_op = 'transpose'
            )
        return Tensor(self.data.transpose())
                         
    def mm(self, x):
        if (self.autograd):
            return Tensor(
                self.data.dot(x.data),
                autograd = True,
                creators = [self, x],
                creation_op = 'mm'
            )
        return Tensor(self.data.dot(x.data))
                         
    
    def sigmoid(self):
        if (self.autograd):
            return Tensor(
                1 / (1 + np.exp(-self.data)),
                autograd = True,
                creators = [self],
                creation_op = 'sigmoid'
            )
        return Tensor(1 / (1 + np.exp(-self.data)))
                         
        
    def tanh(self):
        if (self.autograd):
            return Tensor(
                np.tanh(self.data),
                autograd = True,
                creators = [self],
                creation_op = 'tanh'
            )
        return Tensor(np.tanh(self.data))
                         
    
    def index_select(self, indices):
        if (self.autograd):
            new = Tensor(
                self.data[indices.data],
                autograd = True,
                creators = [self],
                creation_op = 'index_select'
            )
            new.index_select_indices = indices
            return new
        return Tensor(self.data[indices.data])
                         
    
    def cross_entropy(self, target_indices):
        temp = np.exp(self.data)
        softmax_output = temp / np.sum(
            temp,
            axis = len(self.data.shape) - 1,
            keepdims = True
        )
        t = target_indices.data.flatten()
        p = softmax_output.reshape(len(t), -1)
        target_dist = np.eye(p.shape[1])[t]
        loss = -(np.log(p) * (target_dist)).sum(1).mean()
        
        if (self.autograd):
            out = Tensor(
                loss,
                autograd = True,
                creators = [self],
                creation_op = 'cross_entropy'
            )
            out.softmax_output = softmax_output
            out.target_dist = target_dist
            return out
        
        return Tensor(loss)
        
                         
                         
                         
                         
a = Tensor([1, 2, 3, 4, 5], autograd = True)
b = Tensor([2, 2, 2, 2, 2], autograd = True)
c = Tensor([5, 4, 3, 2, 1], autograd = True)

d = a + b
e = b + c
f = d + e

f.backward(Tensor(np.array([1, 1, 1, 1, 1])))

print(b.grad.data == np.array([2, 2, 2, 2, 2]))

print('\n-------------------------\n')

a1 = Tensor([1, 2, 3, 4, 5], autograd = True)
b1 = Tensor([2, 2, 2, 2, 2], autograd = True)
c1 = Tensor([5, 4, 3, 2, 1], autograd = True)

d1 = a1 + (-b1)
e1 = (-b1) + c1
f1 = d1 + e1

f1.backward(Tensor(np.array([1, 1, 1, 1, 1])))
print(b1.grad.data == np.array([-2, -2, -2, -2, -2]))

SyntaxError: invalid syntax (<ipython-input-1-1e3e4082b179>, line 70)

In [ ]:
import numpy
np.random.seed(0)

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target = np.array([[0], [1], [0], [1]])

weights_0_1 = np.random.rand(2, 3)
weights_1_2 = np.random.rand(3, 1)

for i in range(10):
    layer_1 = data.dot(weights_0_1) # predict
    layer_2 = layer_1.dot(weights_1_2)
    
    diff = (layer_2 - target) # Compare
    sqdiff = (diff * diff)
    loss = sqdiff.sum(0) # Mean squared error loss
    
    layer_1_grad = diff.dot(weights_1_2.transpose()) # Learn - this is the backpropagation piece
    weight_1_2_update = layer_1.transpose().dot(diff)
    weight_0_1_update = data.transpose().dot(layer_1_grad)
    
    weights_1_2 -= weight_1_2_update * 0.1
    weights_0_1 -= weight_0_1_update * 0.1
    
    print(loss[0])
    

In [18]:
import numpy as np

np.random.seed(0)

data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

w = list()
w.append(Tensor(np.random.rand(2, 3), autograd = True))
w.append(Tensor(np.random.rand(3, 1), autograd = True))

for i in range(10):
    pred = data.mm(w[0]).mm(w[1]) # Predict
    loss = ((pred - target) * (pred - target)).sum(0) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    
    for w_ in w:
        w_.data -= w_.grad.data * 0.1
        w_.grad_data *= 0
        
    print(loss)
    
    
    

AttributeError: 'Tensor' object has no attribute 'mm'

In [ ]:
# Adding automatic optimization (making stochastic gradient descent optimizer)
                
import numpy as np

np.random.seed(0)


class SGD(object):
    def __init__(self, parameters, alpha = 0.1):
        self.parameters = parameters
        self.alpha = alpha
        
    def zero(self):
        for p in self.parameters:
            p.grad.data *= 0
    
    def step(self, zero = True):
        for p in self.parameters:
            p.data -= p.grad.data * self.alpha
            
            if (zero):
                p.grad.data *= 0



data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

w = list()
w.append(Tensor(np.random.rand(2, 3), autograd = True))
w.append(Tensor(np.random.rand(3, 1), autograd = True))

optim = SGD(parameters = w, alpha = 0.1)

for i in range(10):
    pred = data.mm(w[0]).mm(w[1]) # Predict
    loss = ((pred - target) * (pred - target)).sum(0) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    
    optim.step()

In [ ]:
class Layer(object):
    def __init__(self):
        self.parameters = list()
        
    def get_parameters(self):
        return self.parameters
    
class Linear(Layer):
    def __init__(self, n_inputs, n_outputs):
        super().__init__()
        W = np.random.randn(n_inputs, n_outputs) * np.sqrt(2.0 / (n_inputs))
        self.weight = Tensor(W, autograd = True)
        self.bias = Tensor(np.zeros(n_outputs), autograd = True)
        
        self.parameters.append(self.weight)
        self.parameters.append(self.bias)
        
    def forward(self, input):
        return input.mm(self.weight) + self.bias.expand(0, len(input.data))
    
class Sequential(Layer):
    def __init__(self, layers = list()):
        super().__init__()
        self.layers = layers
        
    def add(self, layer):
        self.layers.append(layer)
        
    def forward(self, input):
        for layer in self.layers:
            input = layer.forward(input)
            
        return input
    
    def get_parameters(self):
        params = list()
        for l in self.layers:
            params += l.get_parameters()
        return params
    
    
class MSELoss(Layer):
    def __init__(self):
        super().__init__()
        
    def forward(self, pred, target):
        return ((pred - target) * (pred - target)).sum(0)
    
# Nonlinearity layers
class Tanh(Layer):
    def __init__(self):
        super().__init__()
        
    def forward(self, input):
        return input.tanh()
    
    
class Sigmoid(Layer):
    def __init__(self):
        super().__init__()
        
    def forward(self, input):
        return input.sigmoid()
    
    
class Embedding(Layer):
    def __init__(self, vocab_size, dim):
        super().__init__()
        
        self.vocab_size = vocab_size
        self.dim = dim
        
        # This initialization style is a convention from word2vec
        weight = (np.random.rand(vocab_size, dim) - 0.5) / dim
        

class CrossEntropyLoss(object):
    def __init__(self):
        super().__init__()
        
    def forward(self, input, target):
        return input.cross_entropy(target)
    
    

class RNNCell(Layer):
    def __init__(self, n_inputs, n_hidden, n_output, activation = 'sigmoid'):
        super().__init__()
        
        self.n_inputs = n_inputs
        self.n_hidden = n_hidden
        self.n_output = n_output
        
        if (activation == 'sigmoid'):
            self.activation = Sigmoid()
        elif (activation == 'tanh'):
            self.activation = Tanh()
        else:
            raise Exception('Non-linearity not found')
        
        self.w_ih = Linear(n_inputs, n_hiddent)
        self.w_hh = Linear(n_hidden, n_hidden)
        self.w_ho = Linear(n_hidden, n_output)
        
        self.parameters += self.w_ih.get_parameters()
        self.parameters += self.w_hh.get_parameters()        
        self.parameters += self.w_ho.get_parameters()   
        
    def forward(self, input, hidden):
        from_prev_hidden = self.w_hh.forward(hidden)
        combined = self.w_ih.forward(input) + from_prev_hidden
        new_hidden = self.activation.forward(combined)
        output = self.w_ho.forward(new_hidden)
        return output, new_hidden
    
    def init_hidden(self, batch_size = 1):
        return Tensor(np.zeros((batch_size, self.n_hidden)), autograd = True)

In [ ]:
# Layers that contain layers

data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

model = Sequential([Linear(2, 3), Linear(3, 1)]) # take a look above

optim = SGD(parameters = model.get_parameters(), alpha = 0.05)

for i in range(10):
    pred = model.forward(data) # Predict
    loss = ((pred - target) * (pred - target)).sum(0) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    optim.step()
    print(loss)

In [ ]:
# Loss functions layers (some layers have no weights)

import numpy as np
np.random.seed(0)

data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

model = Sequential([Linear(2, 3), Linear(3, 1)])
criterion = MSELoss()

optim = SGD(parameters = model.get_parameters(), alpha = 0.05)

for i in range(10):
    pred = model.forward(data) # Predict
    loss = criterion.forward(pred, target) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    optim.step()
    print(loss)



In [ ]:
# Working with nonlinearity layers
import numpy as np
np.random.seed(0)

data = Tensor(np.array([[0, 0], [0, 1], [1, 0], [1, 1]]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

model = Sequential([Linear(2, 3), Tanh(), Linear(3, 1), Sigmoid()])
criterion = MSELoss()

optim = SGD(parameters = model.get_parameters(), alpha = 1)

for i in range(10):
    pred = model.forward(data) # Predict
    loss = criterion.forward(pred, target) # Compare
    loss = backward(Tensor(np.ones_like(loss.data))) # Learn
    optim.step()
    print(loss)
    


In [3]:
import numpy as np

identity = np.eye(5)
print(identity)

print(identity[np.array([[1, 2, 3, 4], [2, 3, 4, 0]])])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[[0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0.]]]


In [ ]:
x = Tensor(np.eye(5), autograd = True)
x.index_select(Tensor([[1, 2, 3], [2, 3, 4]])).backward()
print(x.grad)

In [ ]:
class Embedding(Layer):
    def __init__(self, vocab_size, dim):
        super().__init__()
        
        self.vocab_size = vocab_size
        self.dim = dim
        
        weight = (np.random.rand(vocab_size, dim) - 0.5) / dim
        self.weight = Tensor(weight, autograd = True)
        
        self.parameters.append(self.weight)
        
    def forward(self, input):
        return self.weight.index_select(input)

In [ ]:
data = Tensor(np.array([1, 2, 1, 2]), autograd = True)
target = Tensor(np.array([[0], [1], [0], [1]]), autograd = True)

embed = Embedding(5, 3)
model = Sequential([embed, Tanh(), Linear(3, 1), Sigmoid()])
criterion = MSELoss()

optim = SGD(parameters = model.get_parameters(), alpha = 0.5)

for i in range(10):
    pred = model.forward(data) # Predict
    loss = criterion.forward(pred, target) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    optim.step()
    print(loss)
    


In [ ]:
# Cross Entropy Layer
import numpy as np
np.random.seed(0)

# data indices
data = Tensor(np.array([1, 2, 1, 2]), autograd = True)

# target indices
target = Tensor(np.array([0, 1, 0, 1]), autograd = True)

model = Sequential([Embedding(3, 3), Tanh(), Linear(3, 4)])
criterion = CrossEntropyLoss()

optim = SGD(parameters = model.get_parameters(), alpha = 0.1)

for i in range(10):
    pred = model.forward(data) # Predict
    loss = criterion.forward(pred, target) # Compare
    loss.backward(Tensor(np.ones_like(loss.data))) # Learn
    optim.step()
    print(loss)
    

    


In [ ]:
# The recurrent neural network layer
import sys, random, math
from collections import Counter
import numpy as np

f = open('tasksv11/en/qa1_single-supporting-fact_train.txt', 'r')
raw = f.readlines()
f.close()

tokens = list()
for line in raw[0 : 1000]:
    tokens.append(line.lower().replace('\n', '').split(' ')[1 : ])
    
new_tokens = list()
for line in tokens:
    new_tokens.append(['-'] * (6 - len(line)) + line)
tokens = new_tokens

vocab = set()
for sent in tokens:
    for word in sent:
        vocab.add(word)
        
vocab = list(vocab)

word2index = {}

for i, word in enumerate(vocab):
    word2index[word] = i
    
def words2indices(sentence):
    idx = list()
    for word in sentence:
        idx.append(word2index[word])
    return idx

indices = list()
for line in tokens:
    idx = list()
    for w in line:
        idx.append(word2index[w])
    indices.append(x)
    
data = np.array(indices)


embed = Embedding(vocab_size = len(vocab), dim = 16)
model = RNNCell(n_inputs = 16, n_hidden = 16, n_output = len(vocab))

criterion = CrossEntropyLoss()
params = model.get_parameters() + embed.get_parameters()
optim = SGD(parameters = params, alpha = 0.05)


for iter in range(1000):
    batch_size = 100
    total_loss = 0
    
    hidden = model.init_hidden(batch_size = batch_size)
    
    for t in range(5):
        input = Tensor(data[0 : batch_size, t], autograd = True)
        rnn_input = embed.forward(input = input)
        output, hidden = model.forward(input = rnn_input, hidden = hidden)
        
    target = Tensor(data[0 : batch_size, t + 1], autograd = True)
    loss = criterion.forward(output, target)
    loss.backward()
    optim.step()
    total_loss += loss.data
    if (iter % 200 == 0):
        p_correct = (target.data == np.argmax(output.data, axis = 1)).mean()
        print_loss = total_loss / (len(data) / batch_size)
        print('loss: ', print_loss, '% Correct: ', p_correct)

In [ ]:
batch_size = 1
hidden = model.init_hidden(batch_size = batch_size)

for t in range(5):
    input = Tensor(data[0 : batch_size, t], autograd = True)
    rnn_input = embed.forward(input = input)
    output, hidden = model.forward(input = rnn_input, hidden = hidden)
    
target = Tensor(data[0 : batch_size, t + 1], autograd = True)
loss = criterion.forward(output, target)

ctx = ''
for idx in data[0 : batch_size][0][0 : -1]:
    ctx += vocab[idx] + ' '
    print('Context: ', ctx)
    print('Pred: ', vocab[output.data.argmax()])